version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/apps/cinema"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/apps/engine"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/apps/game"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/apps/podcast"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/apps/website"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/packages/@pauli/cinema-core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/packages/@pauli/engine-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/packages/@pauli/game-engine"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/packages/@pauli/shared"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
